---
- name: Setup YC Instance
  hosts: all
  become: true
  roles:
    - setup
  tags: setup

- name: Remote folder structure
  hosts: all
  become: true
  roles:
    - folder_structure
  tags: folder_structure

- name: Run services on remote host
  hosts: all
  become: true
  roles:
    - run_services
  tags: run

