---
# tasks file for roles/setup
- name: Install dependencies for Ubuntu/Debian
  apt:
    name:
      - ca-certificates
      - gnupg
      - make
      - python3
    state: latest
    update_cache: yes
  when: ansible_facts['os_family'] == "Debian"

- name: Install dependencies for RedHat
  yum:
    name:
      - ca-certificates
      - gnupg
      - make
      - python3
    state: latest
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker GPG key for RedHat
  rpm_key:
    key: https://download.docker.com/linux/centos/gpg
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Add Docker APT repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_facts['distribution_release'] }} stable"
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Add Docker repository for RedHat
  yum_repository:
    name: docker
    description: Docker
    baseurl: https://download.docker.com/linux/centos/7/x86_64/stable
    gpgcheck: 1
    enabled: 1
  when: ansible_facts['os_family'] == "RedHat"

- name: Install Docker
  package:
    name: docker-ce
    state: present
  when: ansible_facts['os_family'] == "Debian"

- name: Install Docker for RedHat
  yum:
    name: docker-ce
    state: present
  when: ansible_facts['os_family'] == "RedHat"

- name: Install docker-compose from GitHub
  get_url:
    url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
    dest: /usr/local/bin/docker-compose
    mode: 'u+x,g+x'

- name: Start and enable Docker service
  service:
    name: docker
    state: started
    enabled: true

- name: Add the user to Docker group
  command: usermod -aG docker "{{ ansible_user }}"

- name: Restart the Docker service to ensure permissions
  service:
    name: docker
    state: restarted

